### ISSUE TITLE
Exception: Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by reverser69** [TheLeftExit/Trickster#1]
hi

I'm using your tool on Mad Max game. it does a fine job of finding types but when i press "read", it throws this error.

detailed log:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.OverflowException: Arithmetic operation resulted in an overflow.
   at TheLeftExit.Memory.Sources.CachedMemory..ctor(UInt64 baseAddress, Int32 size)
   at TheLeftExit.Trickster.TypeScanner.<>c.<InitRegions>b__8_0(MemoryRegionInfo x)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at TheLeftExit.Trickster.TypeScanner.InitRegions()
   at TheLeftExit.Trickster.MainForm.readButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)


```

**Comment by TheLeftExit** [comment]
https://github.com/TheLeftExit/Trickster/blob/079383344d516265c60c3a74d9b49e72399b04d2/Trickster/TypeScanner.cs#L91

I guess this line faults when a memory region exceeds 2^31 bytes. I did not expect memory regions to be this large. Will fix, thanks.

**Comment by reverser69** [comment]
thanks for instant reply.
this game has tons of functions to explore and I'm going to report a lot, while doing so. i hope you don't mind.

**Comment by TheLeftExit** [comment]
No problem, I'd like to fix as many issues as possible, so any feedback is appreciated.

It might take a few days, since [the standard .NET stuff I'm using](https://docs.microsoft.com/en-us/dotnet/api/system.span-1?view=net-6.0) is hardcoded for memory regions under 2 GB, so I'll have to reinvent the wheel in a few places.

**Comment by TheLeftExit** [comment]
Please try this version:
https://github.com/TheLeftExit/Trickster/releases/tag/1.3

**Comment by reverser69** [comment]
thank you very much for this.
the issue is fixed. ill continue to work with it and report back any found issues.

**Comment by TheLeftExit** [comment]
Cool!
